site_name: RadiatedExodus Public Modules Documentation
site_url: https://realethanplayzdev.github.io/
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
plugins:
  - search
  - mkdocs-video
markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RealEthanPlayzDev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RadiatedExodus
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCuLAUKIVWXpzSKgn8U6TllA
    - icon: simple/roblox
      link: https://www.roblox.com/users/664076365/profile
nav:
  - index.md
  - DeviceInfo:
    - DeviceInfo/About.md
    - DeviceInfo/Usage.md
    - API Reference:
      - Functions:
        - GetDevicePlatform(): DeviceInfo/API Reference/func_GetDevicePlatform.md
        - GetDeviceType(): DeviceInfo/API Reference/func_GetDeviceType.md
        - GetDeviceInput(): DeviceInfo/API Reference/func_GetDeviceInput.md
        - GetDeviceOrientation(): DeviceInfo/API Reference/func_GetDeviceOrientation.md
        - GetWindowSize(): DeviceInfo/API Reference/func_GetWindowSize.md
        - GetGraphicsQuality(): DeviceInfo/API Reference/func_GetGraphicsQuality.md
      - Enums (DeviceInfoEnum):
        - PlatformType: DeviceInfo/API Reference/enum_PlatformType.md
        - DeviceType: DeviceInfo/API Reference/enum_DeviceType.md
        - InputType: DeviceInfo/API Reference/enum_InputType.md
        - DeviceOrientation: DeviceInfo/API Reference/enum_DeviceOrientation.md
      - Events:
        - InputChanged: DeviceInfo/API Reference/event_InputChanged.md
        - OrientationChanged: DeviceInfo/API Reference/event_OrientationChanged.md
        - WindowSizeChanged: DeviceInfo/API Reference/event_WindowSizeChanged.md
        - GraphicsQualityChanged: DeviceInfo/API Reference/event_GraphicsQualityChanged.md
  - ColorPickerModule:
    - ColorPickerModule/About.md
    - ColorPickerModule/Usage.md
    - API Reference:
      - Functions:
        - promptPickColor(): ColorPickerModule/API Reference/func_promptPickColor.md
      - Enums (ColorPickerModuleEnum):
        - returnType: ColorPickerModule/API Reference/enum_returnType.md
  - RigConverter:
    - RigConverter/About.md
    - API Reference:
      - Functions:
        - R6(): RigConverter/API Reference/func_R6.md
        - R15(): RigConverter/API Reference/func_R15.md
  - StarGenerator:
    - StarGenerator/About.md
    - API Reference:
      - Functions:
        - Generate(): StarGenerator/API Reference/func_Generate.md
      - Types:
        - posv3: StarGenerator/API Reference/type_posv3.md
        - posnum: StarGenerator/API Reference/type_posnum.md
  - GeometryLinesBackground:
    - GeometryLinesBackground/About.md
    - API Reference:
      - Functions:
        - new(): GeometryLinesBackground/API Reference/func_new.md
        - StartRender(): GeometryLinesBackground/API Reference/func_StartRender.md
        - StopRender(): GeometryLinesBackground/API Reference/func_StopRender.md
        - IsRendering(): GeometryLinesBackground/API Reference/func_IsRendering.md
        - SetAmountOfDots(): GeometryLinesBackground/API Reference/func_SetAmountOfDots.md
        - SetRootFrame(): GeometryLinesBackground/API Reference/func_SetRootFrame.md
        - SetDotBackgroundColor3(): GeometryLinesBackground/API Reference/func_SetDotBackgroundColor3.md
        - SetLineBackgroundColor3(): GeometryLinesBackground/API Reference/func_SetLineBackgroundColor3.md
        - SetTransparencyEnabled(): GeometryLinesBackground/API Reference/func_SetTransparencyEnabled.md
      - Public/exported variables:
        - RootFrame: GeometryLinesBackground/API Reference/publicvar_RootFrame.md
        - AmountOfDots: GeometryLinesBackground/API Reference/publicvar_AmountOfDots.md
        - DotBackgroundColor3: GeometryLinesBackground/API Reference/publicvar_DotBackgroundColor3.md
        - LineBackgroundColor3: GeometryLinesBackground/API Reference/publicvar_LineBackgroundColor3.md
        - TransparencyEnabled: GeometryLinesBackground/API Reference/publicvar_TransparencyEnabled.md
        - Rendering: GeometryLinesBackground/API Reference/publicvar_Rendering.md
  - RESignal:
    - RESignal/About.md
    - API Reference:
      - new(): RESignal/API Reference/func_new.md
      - RESignal.SignalBehavior: RESignal/API Reference/enum_SignalBehavior.md
      - RESignal:
        - Functions:
          - Fire(): RESignal/API Reference/RESignal/func_Fire.md
          - DisconnectAll(): RESignal/API Reference/RESignal/func_DisconnectAll.md
          - Connect(): RESignal/API Reference/RESignal/func_Connect.md
          - ConnectOnce(): RESignal/API Reference/RESignal/func_ConnectOnce.md
          - Wait(): RESignal/API Reference/RESignal/func_Wait.md
          - SetSignalBehavior(): RESignal/API Reference/RESignal/func_SetSignalBehavior.md
          - Destroy(): RESignal/API Reference/RESignal/func_Destroy.md
      - RESignalConnection:
        - Functions:
          - Disconnect(): RESignal/API Reference/RESignalConnection/func_Disconnect.md
        - Public/exposed variables:
          - Connected: RESignal/API Reference/RESignalConnection/publicvar_Connected.md
  - Builder:
    - Builder/About.md
    - Custom classes: Builder/CustomClasses.md
    - API Reference:
      - Types:
        - Description: Builder/API Reference/Types/type_Description.md
      - Builder:
        - About: Builder/API Reference/Builder/About.md
        - Functions:
          - Descriptor: Builder/API Reference/Builder/func_Descriptor.md
          - Event: Builder/API Reference/Builder/func_Event.md
          - Method: Builder/API Reference/Builder/func_Method.md
          - PropertyChangedSignal: Builder/API Reference/Builder/func_PropertyChangedSignal.md
          - Attribute: Builder/API Reference/Builder/func_Attribute.md
          - AttributeChangedSignal: Builder/API Reference/Builder/func_AttributeChangedSignal.md
          - State: Builder/API Reference/Builder/func_State.md
          - MultiState: Builder/API Reference/Builder/func_MultiState.md
          - MultiStateResolvable: Builder/API Reference/Builder/func_MultiStateResolvable.md
          - WrappedTypeof: Builder/API Reference/Builder/func_WrappedTypeof.md
          - WrappedInstanceNew: Builder/API Reference/Builder/func_WrappedInstanceNew.md
          - CreateDescriptorFunctionWithCustomClassLocation: Builder/API Reference/Builder/func_CreateDescriptorFunctionWithCustomClassLocation.md
      - Descriptor:
        - About: Builder/API Reference/Descriptor/About.md
        - Functions:
          - Build(): Builder/API Reference/Descriptor/func_Build.md
        - Public variables:
          - Class: Builder/API Reference/Descriptor/publicvar_Class.md
          - Description: Builder/API Reference/Descriptor/publicvar_Description.md
          - CustomClassesLocation: Builder/API Reference/Descriptor/publicvar_CustomClassesLocation.md
      - Event:
        - About: Builder/API Reference/Event/About.md
        - Functions:
          - Resolve(): Builder/API Reference/Event/func_Resolve.md
        - Public variables:
          - Target: Builder/API Reference/Event/publicvar_Target.md
      - Method:
        - About: Builder/API Reference/Method/About.md
        - Functions:
          - Resolve(): Builder/API Reference/Method/func_Resolve.md
        - Public variables:
          - Target: Builder/API Reference/Method/publicvar_Target.md
      - PropertyChangedSignal:
        - About: Builder/API Reference/PropertyChangedSignal/About.md
        - Functions:
          - Resolve(): Builder/API Reference/PropertyChangedSignal/func_Resolve.md
        - Public variables:
          - Target: Builder/API Reference/PropertyChangedSignal/publicvar_Target.md
      - Attribute:
        - About: Builder/API Reference/Attribute/About.md
        - Functions:
          - Resolve(): Builder/API Reference/Attribute/func_Resolve.md
        - Public variables:
          - Target: Builder/API Reference/Attribute/publicvar_Target.md
      - AttributeChangedSignal:
        - About: Builder/API Reference/AttributeChangedSignal/About.md
        - Functions:
          - Resolve(): Builder/API Reference/AttributeChangedSignal/func_Resolve.md
        - Public variables:
          - Target: Builder/API Reference/AttributeChangedSignal/publicvar_Target.md
      - MultiStateResolvable:
        - About: Builder/API Reference/MultiStateResolvable/About.md
        - Functions:
          - Resolve(): Builder/API Reference/MultiStateResolvable/func_Resolve.md
        - Public variables:
          - Target: Builder/API Reference/MultiStateResolvable/publicvar_Target.md
          - MultiState: Builder/API Reference/MultiStateResolvable/publicvar_MultiState.md
      - State:
        - About: Builder/API Reference/State/About.md
        - Functions:
          - Get(): Builder/API Reference/State/func_Get.md
          - Set(): Builder/API Reference/State/func_Set.md
        - Public variables:
          - Value: Builder/API Reference/State/publicvar_Value.md
        - Events:
          - OnChanged: Builder/API Reference/State/event_OnChanged.md
      - MultiState:
        - About: Builder/API Reference/MultiState/About.md
        - Functions:
          - Get(): Builder/API Reference/MultiState/func_Get.md
          - Set(): Builder/API Reference/MultiState/func_Set.md
        - Public variables:
          - States: Builder/API Reference/MultiState/publicvar_States.md
        - Events:
          - OnChanged: Builder/API Reference/MultiState/event_OnChanged.md
      - Resolvable:
        - About: Builder/API Reference/Resolvable/About.md
        - Functions:
          - Resolve(): Builder/API Reference/Resolvable/func_Resolve.md
